version: '2'
# export DATABASE_URL=mysql2://root:rootsecret@127.0.0.1:23306/amrc_development
# export DATABASE_TEST_URL=mysql2://root:rootsecret@127.0.0.1:23306/amrc_test
# export DATABASE_URL=postgresql://postgres:example@127.0.0.1:25432/amrc_production
services:
  db:
    image: postgres
    restart: always
    ports:
      - "25432:5432"
    environment:
      POSTGRES_PASSWORD: example
